votaprato/config/routes.rb
Votaprato::Application.routes.draw do

  resources :qualificacaes

  resources :clientes

  match ':controller(/:action(/:id(.:format)))'

  match 'rack', :to => 
         proc{|env| [ 200 \
                    , {"Content-Type" => "text/html"} \
                    , ["App Rack numa rota Rails"]    \
                    ]     \
         }

end

votaprato/app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

votaprato/app/models/mailer_observer.rb
class MailerObserver < ActiveRecord::Observer
  observe :registration, :user

  def after_create(model)
    # code to send confirmation email...
  end
end

votaprato/app/models/qualificacao.rb
class Qualificacao < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :restaurante
end

votaprato/app/models/restaurante.rb
class Restaurante < ActiveRecord::Base
end

votaprato/app/models/restaurante_observer.rb
class RestauranteObserver < ActiveRecord::Observer
  def after_create(model)
    # code to confirm via email
  end
end

votaprato/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery

end

votaprato/app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  # GET /clientes
  # GET /clientes.xml
  def index
    @clientes = Cliente.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.xml
  def show
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.xml
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.xml
  def create
    @cliente = Cliente.new(params[:cliente])

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to(@cliente, :notice => 'Cliente was successfully created.') }
        format.xml  { render :xml => @cliente, :status => :created, :location => @cliente }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cliente.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.xml
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to(@cliente, :notice => 'Cliente was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cliente.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.xml
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to(clientes_url) }
      format.xml  { head :ok }
    end
  end
end

votaprato/app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController

  def hello
    render :text => "HelloWorldController: hello: Olá mundo!!!"
  end

  def index
    # redirect_to :action => 'hello'
    render :text => "HelloWorldController: index: Olá mundo!!!"
  end

end

votaprato/app/controllers/qualificacaes_controller.rb
class QualificacaesController < ApplicationController
  # GET /qualificacaes
  # GET /qualificacaes.xml
  def index
    @qualificacaes = Qualificacao.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @qualificacaes }
    end
  end

  # GET /qualificacaes/1
  # GET /qualificacaes/1.xml
  def show
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @qualificacao }
    end
  end

  # GET /qualificacaes/new
  # GET /qualificacaes/new.xml
  def new
    @qualificacao = Qualificacao.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @qualificacao }
    end
  end

  # GET /qualificacaes/1/edit
  def edit
    @qualificacao = Qualificacao.find(params[:id])
  end

  # POST /qualificacaes
  # POST /qualificacaes.xml
  def create
    @qualificacao = Qualificacao.new(params[:qualificacao])

    respond_to do |format|
      if @qualificacao.save
        format.html { redirect_to(@qualificacao, :notice => 'Qualificacao was successfully created.') }
        format.xml  { render :xml => @qualificacao, :status => :created, :location => @qualificacao }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @qualificacao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /qualificacaes/1
  # PUT /qualificacaes/1.xml
  def update
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      if @qualificacao.update_attributes(params[:qualificacao])
        format.html { redirect_to(@qualificacao, :notice => 'Qualificacao was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @qualificacao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /qualificacaes/1
  # DELETE /qualificacaes/1.xml
  def destroy
    @qualificacao = Qualificacao.find(params[:id])
    @qualificacao.destroy

    respond_to do |format|
      format.html { redirect_to(qualificacaes_url) }
      format.xml  { head :ok }
    end
  end
end

votaprato/app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController

  def index
    @restaurantes = Restaurante.order("name")
  end

  def show
    @restaurante = Restaurante.find( params[:id] )
  end

  def new
    @restaurante = Restaurante.new
  end   # using default: sending to new.html.erb

  def create
    @restaurante = Restaurante.new( params[:restaurante] )

    if @restaurante.save
      redirect_to(:action => "show", :id => @restaurante)
    else
      render :action => "new"
    end
  end   # receives "POST" from new.html.erb

  def edit
    @restaurante = Restaurante.find( params[:id] )
  end   # edit.html.erb

  def update
    @restaurante = Restaurante.find( params[:id] )
    if @restaurante.update_attributes( params[:restaurante] )
      redirect_to(:action => "show", :id => @restaurante)
    else
      render :action => "edit"
    end
  end

  def destroy
    @restaurante = Restaurante.find( params[:id] )
    @restaurante.destroy
    redirect_to :action => "index" # I have no destroy.html.erb, so I redirect
  end


end

votaprato/app/helpers/application_helper.rb
module ApplicationHelper

  def menu_principal
    menu = %w(cliente qualificacao restaurante)

    menu_principal = "<menu><ul>"
    menu.each do |item|

      menu_principal << "<li>" +
                        link_to(item, :controller => item.pluralize) +
                        "</li>"

    end
    menu_principal << "</ul></menu>"

    raw menu_principal

  end

end

votaprato/app/helpers/clientes_helper.rb
module ClientesHelper
end

votaprato/app/helpers/hello_world_helper.rb
module HelloWorldHelper
end

votaprato/app/helpers/qualificacaes_helper.rb
module QualificacaesHelper
end

votaprato/app/helpers/restaurates_helper.rb
module RestauratesHelper
end

votaprato/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Votaprato</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>

<h5>Controle de Restaurantes™</h5>

<body>

  <%= menu_principal %>

  <p style="color: green"><%= flash[:notice] %></p>

  <% flash.each do |key,msg| %>
    <%= content_tag :p, msg, :class => "flash-#{key}"%>
  <% end %>

  <%= yield %>

</body>
</html>

votaprato/app/views/qualificacaes/_form.html.erb
<%= form_for(@qualificacao) do |f| %>
  <% if @qualificacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qualificacao.errors.count, "error") %> prohibited this qualificacao from being saved:</h2>

      <ul>
      <% @qualificacao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cliente_id %><br />

    <%= f.collection_select( :cliente_id            \
                           , Cliente.order('nome')  \
                           , :id                    \
                           , :nome                  \
                           , {:prompt => true}      \
                           ) %>
  </div>

  <div class="field">
    <%= f.label :restaurante_id %><br />

    <%= f.collection_select( :restaurante_id            \
                           , Restaurante.order('name')  \
                           , :id                        \
                           , :name                      \
                           , {:prompt => true}          \
                           ) %>

  </div>
  <div class="field">
    <%= f.label :nota %><br />
    <%= f.text_field :nota %>
  </div>
  <div class="field">
    <%= f.label :valor_gasto %><br />
    <%= f.text_field :valor_gasto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

votaprato/app/views/qualificacaes/edit.html.erb
<h1>Editing qualificacao</h1>

<%= render 'form' %>

<%= link_to 'Show', @qualificacao %> |
<%= link_to 'Back', qualificacaes_path %>

votaprato/app/views/qualificacaes/index.html.erb
<h1>Listing qualificacaes</h1>

<table>
  <tr>
    <th>Cliente</th>
    <th>Restaurante</th>
    <th>Nota</th>
    <th>Valor gasto</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @qualificacaes.each do |qualificacao| %>
  <tr>
    <td><%= qualificacao.cliente.nome %></td>
    <td><%= qualificacao.restaurante.name %></td>
    <td><%= qualificacao.nota %></td>
    <td><%= qualificacao.valor_gasto %></td>
    <td><%= link_to 'Show', qualificacao %></td>
    <td><%= link_to 'Edit', edit_qualificacao_path(qualificacao) %></td>
    <td><%= link_to 'Destroy', qualificacao, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Qualificacao', new_qualificacao_path %>

votaprato/app/views/qualificacaes/new.html.erb
<h1>New qualificacao</h1>

<%= render 'form' %>

<%= link_to 'Back', qualificacaes_path %>

votaprato/app/views/qualificacaes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cliente:</b>
  <%= @qualificacao.cliente.nome %>
</p>

<p>
  <b>Restaurante:</b>
  <%= @qualificacao.restaurante.name %>
</p>

<p>
  <b>Nota:</b>
  <%= @qualificacao.nota %>
</p>

<p>
  <b>Valor gasto:</b>
  <%= @qualificacao.valor_gasto %>
</p>


<%= link_to 'Edit', edit_qualificacao_path(@qualificacao) %> |
<%= link_to 'Back', qualificacaes_path %>

votaprato/app/views/restaurantes/edit.html.erb
<h1>Editando Restaurante</h1>

<% if @restaurante.errors.any? %>
  <ul>
    <% @restaurante.errors.full_messages.each do |msg| %>

      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for :restaurante, :url => { :action => 'update', :id => @restaurante } do |f| %>
  
  Name: <%= f.text_field :name %><br/>
  Endereco: <%= f.text_field :endereco %><br/>
  Especialidade: <%= f.text_field :especialidade %><br/>

  <br/><br/>
  <%= submit_tag 'UpdateNow!' %><br/><br/>

<% end %>

<%= link_to 'Back?', { :action => 'index' } %>

votaprato/app/views/restaurantes/index.html.erb
<%# <%= render :partial => 'shared/nome_da_app' %> 

<h1>Listagem de Restaurantes</h1>

<table cellspacing="0" >
  <tr>
    <th>Nome</th>
    <th>Endereco</th>
    <th>Especialidade</th>
    <th colspan="3"> </th>
  </tr>

  <% @restaurantes.each do |rest| %>
    <tr>
      <td><%= rest.name %></td>
      <td><%= rest.endereco %></td>
      <td><%= rest.especialidade %></td>
      <td><%= link_to 'Show', { :action => 'show', :id => rest } %></td>
      <td><%= link_to 'Edit', { :action => 'edit', :id => rest } %></td>
      <td><%= link_to 'Destroy!!', { :action => 'destroy',  :id => rest } %></td>
    </tr>
  <% end %>
</table>

<br/><br/>

<%= link_to 'New restaurante <aqui>', { :action => 'new' } %>

    

votaprato/app/views/restaurantes/new.html.erb
<h1>Restaurante: NewNewNew</h1>

<% if @restaurante.errors.any? %>
  <ul>
    <% @restaurante.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for :restaurante, :url => {:action => 'create'} do |f| %>

  <%= f.label      :name %>
  <%= f.text_field :name %><br/>

  <%= f.label      :endereco %>
  <%= f.text_field :endereco %><br/>

  <%= f.label      :especialidade %>
  <%= f.text_field :especialidade %><br/>

  <br/><br/>
  <%= submit_tag "Enviar" %><br/><br/>

<% end %>

<%= link_to 'Back2Back', { :action => 'index' } %>

votaprato/app/views/restaurantes/new0.html.erb
<form action="/restaurantes" method="post">
  <p>Nome: <input type="text" name="restaurante[name]"></p>
  <p>End : <input type="text" name="restaurante[endereco]"></p>
  <p>Especialidade: <input type="text" name="restaurante[especialidade]"></p>
  <input type="submit">
</form>

votaprato/app/views/restaurantes/show.html.erb
<h1>Restaurante: detalhes</h1>

<p>
  <b>Nome: </b>
  <%= @restaurante.name %>
</p>

<p>
  <b>Endereco: </b>
  <%= @restaurante.endereco %>
</p>

<p>
  <b>Especialidade: </b>
  <%= @restaurante.especialidade %>
</p>


<%= link_to 'Edit', { :action => 'edit', :id => @restaurante } %>
<%= link_to 'Back', { :action => 'index' } %>